name: ci
on: [push]
permissions:
  contents: write
jobs:
  ci:
    name: "ci"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - run: npm install
      - run: npm run ci:fmt
      - run: npm run ci:lint
      - run: npm run ci:build
      - run: npm run ci:test

      - name: "Versioning"
        id: version
        if: github.ref == 'refs/heads/main' && startsWith(github.event.head_commit.message, 'v=')
        env:
          MSG: ${{ github.event.head_commit.message }}
        run: |
          if echo 'if (!/^v=([0-9]+\.){2}[0-9]+$/g.test(process.env.MSG||"")) process.exit(1)' | node; then
            echo deploy=yes >> $GITHUB_OUTPUT
            echo version=v$(echo $MSG | cut -c 3-) >> $GITHUB_OUTPUT
          fi


      - name: "Deployment"
        if: ${{ steps.version.outputs.deploy == 'yes' }}
        env:
          VERSION: ${{ steps.version.outputs.version }}
        run: |
          npm run ci:prune
          git add .
          git config user.name github-actions
          git config user.email github-actions@github.com
          git commit -m release
          git tag -f $VERSION
          git push -fu origin $VERSION
          

