name: Quality Assurance
on: [push, pull_request, workflow_call]
permissions:
  contents: read
  actions: read
  security-events: write
jobs:
  fmt:
    name: Format
    runs-on: ubuntu-22.04
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install
      - run: npm run ci:fmt
  lint:
    name: Lint
    runs-on: ubuntu-22.04
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install
      - run: npm run ci:lint
  test:
    name: Test
    runs-on: ubuntu-22.04
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install
      - run: npm run ci:test
  build:
    name: Build
    runs-on: ubuntu-22.04
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install
      - run: npm run ci:build
  codeql:
    name: CodeQL
    runs-on: ubuntu-22.04
    steps:
      # prepare
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      # init
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: javascript, typescript
      # build code
      - name: Builde code
        run: npm install && npm run ci:build && npm prune --production
      # analyze
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
